### PR TITLE
Added support for Content Security Policy

### PR DESCRIPTION
**Pull request by gavinwahl**
In order to use debug toolbar with a content security policy enabled, no
inline scripts or styles can be used. This commit replaces all `style`
attributes with CSS or javascript. It uses `data` attributes to handle
the dynamic styles, like width and color.

In addition, this required updating jQuery to 1.8, because 1.7 is not
CSP compatible.

See also #307, which began implementing CSP compatibility.

### CODE REVIEW

**Comment by danpalmer** [comment]
Can someone take a look at this? It would be really useful for the project to be as conservative as possible in supported CSPs, so that development environment can differ as little as possible from production.

**Comment by gavinwahl** [comment]
I started working on this again and updated the pull request. I have it working with RENDER_PANELS=True, but with RENDER_PANELS=False it's tricky.

When rendering panels lazily, debug toolbar fetches their content over xhr and then inserts them with $.html. When you do $.html('<script src="http://foo"></script>') in jquery, it doesn't actually insert a script tag into the dom -- it retrieves the script source with xhr and then evals it (see _evalUrl), which of course doesn't work with CSP. I'm not sure how to fix this.

**Comment by graingert** [comment]
@gavinwahl nice one, thanks for taking another look at this 2yo PR!

What is the Google api Ajax URL for, and why is it not https?

**Comment by gavinwahl** [comment]
It's for debug toolbar to load it's jquery (JQUERY_URL). It should actually be `//ajax.googleapis.com/` to allow https.

**Comment by danpalmer** [comment]
Unless we want to bundle jQuery (which I'm pretty sure we don't!) then we will have to have that exception, so I suggest we document it.

With regards to the other parts, allowing `self` makes sense, and is pretty reasonable, but it would be nice to remove the dependency on `img-src data:;`. Is that possible to remove?

**Comment by graingert** [comment]
@gavinwahl I'm right in thinking that JQUERY_URL can point to a self hosted jQuery JS.

**Comment by gavinwahl** [comment]
data: is used for some icons: https://github.com/django-debug-toolbar/django-debug-toolbar/blob/master/debug_toolbar/static/debug_toolbar/css/toolbar.css#L150. I suppose they could be put into files instead. I'm not sure if there's any security problem with allow data urls for images.

Regarding the rest of the policy, this is not the purview of debug toolbar. It doesn't set the header itself, that's up to you and you can use whatever policy you like. If you set JQUERY_URL to something local, feel free to remove ajax.googleapis.com from script-src.

I only mentioned the policy I used so we could document a policy that works with the default toolbar config.

**Comment by graingert** [comment]
@gavinwahl With data-uri images you can place a transparant gif over the top of your bank balance and trick a user into sending the incorrect amount to an attacker.

They can also be slower than multiple files in lots of places.

Please put these in separate files if you have time.

**Comment by graingert** [comment]
Some of these might also look better as Unicode glyphs

**Comment by aaugustin** [comment]
Since the debug toolbar is intended for local use, it shouldn't be optimized for speed, only for ease of maintenance and development.

**Comment by gavinwahl** [comment]
I opened jquery/jquery#2012 for the script thing

**Comment by gavinwahl** [comment]
Looks like the jquery thing isn't going to be fixed until jquery 3.0 is released. I'm not aware of a workaround, so we'll just have to document that you must either use RENDER_PANELS=False or jquery>=3.0. What section of the docs can these notes about CSP support go?

**Comment by graingert** [comment]
@gavinwahl you can get this working in jQuery 2.x by triggering:

```javascript
if ( code.indexOf("use strict") === 1 ) {
    script = document.createElement("script");
    script.text = code;
    document.head.appendChild( script ).parentNode.removeChild( script );
} else {
```

**Comment by gavinwahl** [comment]
No, I saw that too and tried it. Notice that it's putting the source code of the script in script.text -- this is an inline script, which CSP blocks.

**Comment by graingert** [comment]
urgh yeah I didn't spot that.

**Comment by graingert** [comment]
@gavinwahl can you use:

```javascript
$(selector)[0].innerHTML = htmlString;
```

**Comment by gavinwahl** [comment]
Script tags inserted with innerHTML are not executed. That's the reason why jQuery is doing this stuff in the first place.

**Comment by graingert** [comment]
Can we load the scripts statically and the content dynamically?

**Comment by gavinwahl** [comment]
Yes, we could load the scripts for all the builtin panels in base.html, where toolbar.js is loaded. Third-party panels would be unable to load scripts then.

**Comment by graingert** [comment]
How about getting a copy of the jQuery 3.0 .html function and including it
here?

**Comment by gavinwahl** [comment]
That doesn't seem feasible, it's actually functions that are indirectly used by .html(). We'd have to monkey patch jquery's _evalUrl function to do it, but we reuse a jquery that's already on the page. It'd be rude to go about monkey patching some else's copy of jquery.

**Comment by gavinwahl** [comment]
I don't think there's going to be any workaround for the jquery thing, so we'll just have to document that you must either use RENDER_PANELS=False or jquery>=3.0 for CSP compatibility. What section of the docs can these notes about CSP support go?

**Comment by graingert** [comment]
I've rebased and fixed the tests in #704

**Comment by tim-schilling** [comment]
Closing this since #704 was merged in.

**Pull request closed without merging**
