### PR TITLE
Added test target for Django 1.10

### PR DESCRIPTION
**Pull request by claudep**

### CODE REVIEW

**Comment by claudep** [comment]
I'm not there yet, Django <1.11 tells: Requirement already satisfied. And Django >=1.10 doesn't take 1.10.a1 into account...

**Comment by claudep** [comment]
Seems "Django<1.11,>=1.10a" works. Is it the right expression?

**Comment by MarkusH** [comment]
You want to set `pip_pre=True` in tox: http://testrun.org/tox/latest/config.html#confval-pip_pre=True|False(default)

**Comment by claudep** [comment]
I think I'm satisfied with the PR now!

**Pull request merged**
