### PR TITLE
Check User IP from HTTP_X_FORWARDED_FOR http header if exist

### PR DESCRIPTION
**Pull request by appsolute**
Check User IP from HTTP_X_FORWARDED_FOR http header if exist

### CODE REVIEW

**Comment by aaugustin** [comment]
Django used to contain logic along these lines, which was removed for security reasons, in 1.4 or perhaps earlier. I don't want to introduce a similar vulnerability in the debug toolbar, all the more since it can leak sensitive information.

**Comment by appsolute** [comment]
Ok if this's about security reason I do agree with you.
So, Do you know any solutions for the Django application that run behind proxy (reverse proxy) or run with in docker (in my case) to allow only admin to access Debug Toolbar?

**Comment by tim-schilling** [comment]
You can use your own function and specify it as the ```SHOW_TOOLBAR_CALLBACK``` in the [toolbar configuration](http://django-debug-toolbar.readthedocs.org/en/1.3/configuration.html#debug-toolbar-config).

**Comment by aaugustin** [comment]
Or write a middleware to extract the actual IP and put it in `REMOTE_ADDR`.

**Comment by appsolute** [comment]
Thank you @aaugustin, I'll try this solution.
Also thank you @tim-schilling.

**Pull request closed without merging**
