### PR TITLE
:bug: fix repeat record on cache panel

### PR DESCRIPTION
**Pull request by lovemyliwu**

### CODE REVIEW

**Comment by aaugustin** [comment]
How can this bug be triggered?

**Comment by lovemyliwu** [comment]
from some template tags logic

**Comment by aaugustin** [comment]
I'm afraid it's going to be hard to reproduce the bug, let alone write a test case, based on the information you provided.

**Comment by lovemyliwu** [comment]
sorry, I found the issue from django cms tags, hard to say the root cause why proxy class wrapper on a proxy class.

**Pull request closed without merging**
