### PR TITLE
Fix jQuery events priority

### LINKED ISSUE #677: jQuery click events handlers priority conflicts with Angular.js
Angular.js listens for click events on $('html') element for navigation purpose. I don't know why they use such approach, but it results in conflict with dj-debug-toolbar.

toolbar.js adds delegated handlers to $(document), but angular.js handles this events in the first instance, thus every click in debug-toolbar leads to page reloading.

Handlers bound to $('html') are executed before $(document)

### PR DESCRIPTION
**Pull request by nailgun**
Fix #677

### CODE REVIEW

**Comment by tim-schilling** [comment]
There looks to be a number of other event handlers bound to ```document``` in toolbar.js. Lines 138, 157, 171, and 233. Do these also need to be updated?

**Comment by tim-schilling** [comment]
@nailgun can you let me know if those lines also need to be updated?

**Comment by nailgun** [comment]
@tim-schilling No. These are global namespaced events, they don't cause any problems.

**Comment by tim-schilling** [comment]
Thank you for the PR!

**Pull request merged**
