### PR TITLE
Mentioned the Pympler panel in the docs

### PR DESCRIPTION
**Pull request by thedrow**

### CODE REVIEW

**Comment by thedrow** [comment]
ping @aaugustin and @tim-schilling 
Any reason not to merge this?

**Comment by tim-schilling** [comment]
I'll get it merged in tonight.

**Comment by thedrow** [comment]
Thanks :)

**Comment by tim-schilling** [comment]
Rebased and moved it to be in alphabetical order in commit d1d3d611fd017dc21e47b40673ff99941d209cf0.

**Pull request closed without merging**
