### PR TITLE
Fixed Django1.8 support (template panel still requires a Django engine t...

### PR DESCRIPTION
**Pull request by apollo13**
...o be defined)

### CODE REVIEW

**Comment by orokusaki** [comment]
Will this pull request be merged when 1.8b1 is released?

**Comment by hanleyhansen** [comment]
Anyone know when this will go in?

**Comment by tim-schilling** [comment]
@aaugustin What do you think of creating a specific file to handle the different imports/functions based on the versions of Django? It should help restrict all the if/else logic into a single file and keep the rest of the project ignorant of it.

**Comment by aaugustin** [comment]
@tim-schilling Yes, something like `debug_toolbar.compat` would be useful, especially when removing support for older Django versions.

**Comment by aaugustin** [comment]
@tim-schilling Do you intend to work on this within the next few days?

**Comment by tim-schilling** [comment]
I might not get to it until late this week or this weekend, but yes.

**Comment by aaugustin** [comment]
I won't have time before the weekend either.

It would be good to upload a 1.8-compatible release as soon as possible. I suggest the first of us who has time writes the patch and the other reviews it :-)

**Comment by aaugustin** [comment]
As of 22473d36346901b3320f1bf25f4f602d8ded6d04 tests pass on Django 1.8 beta 1.

**Pull request closed without merging**
