### PR TITLE
Start SQLWarningsPanel to warn non-scalable SQL statement

### PR DESCRIPTION
**Pull request by mrkschan**
Introduced a SQLWarningsPanel to detect any non-scalable SQL statement using EXPLAIN. Included some simple warnings for MySQL EXPLAIN.

#688

### CODE REVIEW

**Comment by tim-schilling** [comment]
I'm still on the fence about including a panel that only works with one vendor. It seems better suited to be a third party panel until there's support for others.

**Comment by aaugustin** [comment]
Yes, I agree that this seems more appropriate as a third-party panel. We can link to it in the docs as soon as it's released.

**Comment by mrkschan** [comment]
Let's close this until it has more vendors :)

**Comment by mrkschan** [comment]
Let's close this until it has more vendors :)

**Pull request closed without merging**
